# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

on: [push, pull_request]

name: Basic

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: unit-test
          args: --locked
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: wasm
          args: --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Install stable Rust
        run: cargo make install-stable

      - name: Install nightly Rust
        run: cargo make install-nightly

      # selecting a toolchain should happen before the plugin, as the cache uses the current rustc version as its cache key
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo make fmt

      - name: Run cargo clippy
        run: cargo make clippy

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: schema
          args: --locked

      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
